services:
  - type: web
    name: mortgauge-django-api
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: mortgauge-django-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: mortgauge-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app

databases:
  - name: mortgauge-db
    databaseName: mortgauge
    user: mortgauge_user
    plan: free 